### ISSUE TITLE
[native-comp branch] not top level in wrap-native for #<subr read-key-sequence-vector> (duplicate #65)

### ISSUE THREAD

**Issue by yantar92** [lastquestion/explain-pause-mode#85] opened 2020-07-25 02:34 UTC
Explain-pause-mode: please report this bug by creating a Github
issue at https://github.com/lastquestion/explain-pause-mode. Explain-pause-mode
is now _disabled_ so you can continue to hopefully use Emacs. Info follows:

explain-pause version: 0.1
emacs version: 28.0.50

not top level in wrap-native for #<subr read-key-sequence-vector>
current
#s(explain-pause-command-record root-emacs nil nil 220804 (24347 38889 59780 614000) nil nil nil nil 0)

Backtrace:
(explain-pause-report-measuring-bug "not top level in wrap-native for #<subr read-key-s..." "current" #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 220804 :entry-snap (24347 38889 59780 614000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0))
(explain-pause--wrap-native #<subr read-key-sequence-vector> "C-c-" nil t)
(apply explain-pause--wrap-native #<subr read-key-sequence-vector> ("C-c-" nil t))
(read-key-sequence-vector "C-c-" nil t)
(read-key "C-c-")
(boon-c-god)
(#<subr funcall-interactively> boon-c-god)
(apply #<subr funcall-interactively> boon-c-god)
(funcall-interactively boon-c-god)
(command-execute boon-c-god)

**Comment by yantar92** [comment] 2020-07-25 02:34
This an many other errors are popping up when using native-comp branch of Emacs.

**Comment by yantar92** [comment] 2020-07-25 07:33
Here is another example:

```
Debugger entered--Lisp error: (wrong-type-argument characterp "  (explain-pause-report-measuring-bug \"not top lev...")
  (char-to-string "  (explain-pause-report-measuring-bug \"not top lev...")
  (org-agenda-get-restriction-and-command nil)
  (#f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil nil nil)
  (ad-Advice-org-agenda #f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil)
  (apply ad-Advice-org-agenda #f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil)
  (org-agenda nil)
  (#<subr funcall-interactively> org-agenda nil)
  (apply #<subr funcall-interactively> (org-agenda nil))
  (funcall-interactively org-agenda nil)
  (command-execute org-agenda)

```

Explain-pause-mode: please report this bug by creating a Github
issue at https://github.com/lastquestion/explain-pause-mode. Explain-pause-mode
is now _disabled_ so you can continue to hopefully use Emacs. Info follows:

explain-pause version: 0.1
emacs version: 28.0.50

not top level in wrap-native for #<subr read-char-exclusive>
current
#s(explain-pause-command-record root-emacs nil nil 13524 (24347 57304 189272 572000) nil nil nil nil 0)

Backtrace:
  (explain-pause-report-measuring-bug "not top level in wrap-native for #<subr read-char-..." "current" #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 13524 :entry-snap (24347 57304 189272 572000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0))
  (explain-pause--wrap-native #<subr read-char-exclusive>)
  (apply explain-pause--wrap-native #<subr read-char-exclusive> nil)
  (read-char-exclusive)
  (org-agenda-get-restriction-and-command nil)
  (#f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil nil nil)
  (ad-Advice-org-agenda #f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil)
  (apply ad-Advice-org-agenda #f(compiled-function (&optional arg org-keys restriction) (interactive "P") #<bytecode -0x1c68e98405cf29a6>) nil)
  (org-agenda nil)
  (#<subr funcall-interactively> org-agenda nil)
  (apply #<subr funcall-interactively> (org-agenda nil))
  (funcall-interactively org-agenda nil)
  (command-execute org-agenda)

**Comment by lastquestion** [comment] 2020-07-27 09:29
Hi @yantar92 , thanks for reporting this!

This is a duplicate of #65, and I'm pretty sure the root cuase is because `native-comp` branch doesn't honor the `advice-add`. Please follow me over there to that issue. :_)

If you have time, I have a hypothetical reduced repro that should verify my theory. I meant to try and build `native-comp` branch myself and file a bug, but I haven't had time yet.

**Comment by lastquestion** [comment] 2020-07-27 09:30
Closing this as duplicate

**Closed by lastquestion** 2020-07-27 09:30 UTC
Labels: bug, duplicate
